#ifndef _DATABASESQL_
#define _DATABASESQL_
//#include "database.h"
#include "version.h"
#include "databaseTabDef.h"

#define TAB2COL 100

enum    tabIndex        TABINDEX;
#define TABSCRUCTLIST   { tblPersons, tblGenres, tblRoles, tblpathFS, tblMoviesFS, tblMovies, tblPersonsInMovies, tblGenresInMovies, tblDbVersions, tblConfiguration }
#define TABDATATYPES    { "INTEGER" , "SMALLINT" , "DOUBLE", "TEXT", "BOOLEAN" }
#define ROLESNAMES      { "Director", "Writer", "Actor" }

enum CDataType { E_DEF_INT, E_DEFILTERS_SHORT, E_DEF_DOUBLE, E_DEF_STRING, E_DEF_BOOL, E_MAX_TYPES, E_END_TABLE = E_MAX_TYPES };



enum persons            { PERSONS_ID = TAB_PERSONS * TAB2COL, PERSONS_NAME };
enum genres             { GENRES_ID = TAB_GENRES * TAB2COL, GENRES_GENRE };
enum roles              { ROLES_ID = TAB_ROLES * TAB2COL, ROLES_ROLE };
enum pathFS             { PATH_ID = TAB_PATHFS * TAB2COL, PATH_PATH, PATH_ISREAD, PATH_ISSUB, PATH_HIDE, PATH_MAX } ;
enum moviesFS           { FS_ID = TAB_MOVIESFS * TAB2COL, FS_IDPATH, FS_PATH, FS_FILENAME, FS_PHYSICAL, FS_IMDBID, FS_DATEADDED, FS_FILESIZE, FS_SERIE, FS_ANIM, FS_DOC, FS_SHORT, FS_MAX_FIELDS };
enum movies             { MOVIES_IDMOVIE = TAB_MOVIES * TAB2COL, MOVIES_TITLE, MOVIES_TITLEASCII, MOVIES_YEAR, MOVIES_RATED, MOVIES_RUNTIME, MOVIES_PLOT, MOVIES_LANGUAGE, MOVIES_COUNTRY, MOVIES_AWARD, MOVIES_POSTER, MOVIES_METASCORE, MOVIES_IMDBRATING, MOVIES_IMDBVOTES, MOVIES_IMDBID, MOVIES_TYPE, MOVIES_VUE };
enum deftabs            { DEFTABS_ID, DEFTABS_VALUE };
enum personInMovie      { PERSONINMOVIE_IDMOVIE = TAB_PERSONINMOVIE * TAB2COL, PERSONINMOVIE_IDPERSON, PERSONINMOVIE_IDROLE };
enum genreInMovie       { GENREINMOVIE_IDMOVIE = TAB_GENREINMOVIE * TAB2COL, GENREINMOVIE_IDGENRE };
enum dbversions         { DBVER_VERSION = TAB_DBVERSIONS * TAB2COL, DBVER_DATEADDED, DBVER_DESCRIPTION };
enum tabConfiguration   { CONF_INDEX = TAB_CONFIGURATION * TAB2COL, CONF_VAR, CONF_VALUE, CONF_DESCRIPTION };

#endif // _DATABASESQL_